# Generated by Django 4.1 on 2024-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0010_alter_subject_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("login_id", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=20)),
                ("confirmpassword", models.CharField(default="", max_length=20)),
                ("dob", models.DateField(max_length=20)),
                ("address", models.CharField(default="", max_length=50)),
                ("gender", models.CharField(default="", max_length=50)),
                ("mobilenumber", models.CharField(default="", max_length=50)),
                ("role_Id", models.IntegerField()),
                ("role_Name", models.CharField(max_length=50)),
                ("collage_Name", models.CharField(max_length=50)),
                ("parent_Names", models.CharField(max_length=50)),
                ("parent_Contact_Number", models.CharField(default="", max_length=50)),
                ("parent_Occupations", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_ADMISSION",
            },
        ),
    ]
