# Generated by Django 4.1 on 2024-05-23 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0011_admission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission",
            old_name="collage_Name",
            new_name="collageName",
        ),
    ]
