# Generated by Django 4.1 on 2024-05-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0012_rename_collage_name_admission_collagename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carId", models.IntegerField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("dateOfMenufactoring", models.DateField(max_length=20)),
                ("price", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_CAR",
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelType", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "ORS_Model",
            },
        ),
    ]
