# Generated by Django 4.1 on 2024-06-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0013_car_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("product", models.CharField(max_length=50)),
                ("date", models.DateField(max_length=20)),
                ("quantity", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_SHOPPINGCART",
            },
        ),
        migrations.DeleteModel(
            name="Model",
        ),
    ]
