# Generated by Django 4.1 on 2024-06-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0014_shoppingcart_delete_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("dob", models.DateField(max_length=20)),
                ("mobile", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_CONTACT",
            },
        ),
        migrations.AlterField(
            model_name="car",
            name="carId",
            field=models.IntegerField(),
        ),
    ]
