# Generated by Django 4.1 on 2024-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0015_contact_alter_car_carid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("dov", models.DateField(max_length=20)),
                ("mobile", models.CharField(max_length=50)),
                ("decease", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_DECEASE",
            },
        ),
    ]
