# Generated by Django 4.1 on 2024-06-11 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0016_decease"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Decease",
            new_name="Patient",
        ),
        migrations.AlterModelTable(
            name="patient",
            table="ORS_PATIENT",
        ),
    ]
