# Generated by Django 4.1 on 2024-06-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0017_rename_decease_patient_alter_patient_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(max_length=50)),
                ("orderDate", models.DateField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("customer", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_ORDER",
            },
        ),
    ]
