# Generated by Django 4.1 on 2024-06-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0018_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Followup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient", models.CharField(max_length=50)),
                ("doctor", models.CharField(max_length=50)),
                ("visitDate", models.DateField(max_length=20)),
                ("fees", models.IntegerField()),
            ],
            options={
                "db_table": "ORS_FOLLOWUP",
            },
        ),
    ]
