# Generated by Django 4.1 on 2024-06-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0019_followup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("dob", models.DateField(max_length=20)),
                ("vehicleId", models.DateField(max_length=20)),
                ("insuranceAmount", models.IntegerField(max_length=50)),
            ],
            options={
                "db_table": "ORS_OWNER",
            },
        ),
    ]
