# Generated by Django 4.1 on 2024-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0020_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="insuranceAmount",
            field=models.IntegerField(),
        ),
    ]
