# Generated by Django 4.1 on 2024-06-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0021_alter_owner_insuranceamount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="vehicleId",
            field=models.IntegerField(),
        ),
    ]
