# Generated by Django 4.1 on 2024-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0022_alter_owner_vehicleid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="insuranceAmount",
            field=models.FloatField(),
        ),
    ]
