# Generated by Django 4.1 on 2024-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0023_alter_owner_insuranceamount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplierName", models.CharField(max_length=50)),
                ("lastUpdatedDate", models.DateField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("product", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_INVENTORY",
            },
        ),
    ]
