# Generated by Django 4.1 on 2024-06-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0024_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("openDate", models.DateField(max_length=20)),
                ("version", models.FloatField(max_length=20)),
            ],
            options={
                "db_table": "ORS_PROJECT",
            },
        ),
    ]
